// packages/website/src/features/Packages/Interact.tsx
import { GetPackagesQuery } from '@/types/graphql/graphql';
import { FC, useEffect, useMemo, useState } from 'react';
import { Alert, AlertIcon, Box, Flex, Spinner, Text } from '@chakra-ui/react';
import axios from 'axios';
import pako from 'pako';
import { ChainArtifacts } from '@usecannon/builder/src';
import { getOutput } from '@/lib/builder';
import { VersionInfo, VersionSelect } from '@/features/Packages/VersionSelect';

type Package = GetPackagesQuery['packages'][0];
// type Tag = Package['tags'][0];
// type Variant = Tag['variants'][0];

export const Interact: FC<{ p: Package }> = ({ p }) => {
  const [loading, setLoading] = useState(true);
  const [ipfs, setIpfs] = useState<any>({});
  const [selectedVersion, setSelectedVersion] = useState<VersionInfo>();
  const [cannonOutputs, setCannonOutputs] = useState<ChainArtifacts | null>(
    null
  );

  useEffect(() => {
    console.log('selectedVersion', selectedVersion);
    if (!selectedVersion) return;
    // this.$store.dispatch('changeChainId', this.selectedVariant.chain_id, this.$toast) TODO
    setLoading(true);

    const controller = new AbortController();

    axios
      .get(
        `https://ipfs.io/ipfs/${selectedVersion?.ipfs.replace('ipfs://', '')}`,
        { responseType: 'arraybuffer' }
      )
      .then((response) => {
        // Parse IPFS data
        const uint8Array = new Uint8Array(response.data);
        const inflated = pako.inflate(uint8Array);
        const raw = new TextDecoder().decode(inflated);
        const _ipfs = JSON.parse(raw);
        console.log('IPFS:', raw);
        setIpfs(_ipfs);

        // Get Builder Outputs
        setCannonOutputs(getOutput(_ipfs));
      })
      .catch((error) => {
        console.error(error);
      })
      .finally(() => {
        setLoading(false);
      });

    // Vue.nextTick(() => { // TODO
    //   this.scrollToAnchor();
    // });
    return () => {
      controller.abort();
    };
  }, [selectedVersion]);

  const hasProxy = useMemo(() => {
    return (
      ipfs.state && JSON.stringify(ipfs.state).toLowerCase().includes('proxy')
    );
  }, [ipfs]);

  return (
    <Box position="relative">
      <Flex
        py="6"
        mb="8"
        align="center"
        position="sticky"
        top="0"
        bg="blue.900"
        zIndex="1"
        borderBottom="1px solid rgba(255,255,255,0.25)"
      >
        {/*<ConnectWallet /> TODO */}
        <Box ml="auto">
          <VersionSelect p={p} onChange={setSelectedVersion} />
        </Box>
      </Flex>
      <Box mb="8">
        {/*<InteractCommand :packageName="p.name" :variant="selectedVariant" />*/}
      </Box>

      <Alert
        my="8"
        status="warning"
        bg="blue.800"
        borderColor="blue.700"
        borderWidth="1px"
      >
        <AlertIcon />
        <Text fontWeight="bold">
          Review high-risk transactions carefully in your wallet application
          prior to execution.
        </Text>
      </Alert>

      {hasProxy && (
        <Alert
          my="8"
          status="info"
          bg="blue.800"
          borderColor="blue.700"
          borderWidth="1px"
        >
          <AlertIcon />
          <Text>
            If this protocol has a proxy contract, you should typically interact
            with it instead of the other contracts in the package.
          </Text>
        </Alert>
      )}

      {loading ? (
        <Box py="20" textAlign="center">
          <Spinner />
        </Box>
      ) : (
        <Box>
          {/*<ProvisionStep :imports="output" :cannonOutputs="cannonOutputs" /> TODO */}
        </Box>
      )}
    </Box>
  );
};

// packages/website/components/search/Interact.vue
<template>
  <CBox>
    <CFlex
      py="6"
      mb="8"
      align="center"
      position="sticky"
      top="0"
      bg="blue.900"
      zIndex="1"
      borderBottom="1px solid rgba(255,255,255,0.25)"
    >
      <ConnectWallet />
      <CBox ml="auto">
        <VersionSelect :p="p" v-model="selectedVariant" />
      </CBox>
    </CFlex>
    <CBox mb="8">
      <InteractCommand :packageName="p.name" :variant="selectedVariant" />
    </CBox>

    <CAlert
      my="8"
      status="warning"
      bg="blue.800"
      borderColor="blue.700"
      borderWidth="1px"
    >
      <CAlertIcon /><CText fontWeight="bold">
        Review high-risk transactions carefully in your wallet application prior
        to execution.</CText
      >
    </CAlert>

    <CAlert
      v-if="hasProxy"
      my="8"
      status="info"
      bg="blue.800"
      borderColor="blue.700"
      borderWidth="1px"
    >
      <CAlertIcon /><CText>
        If this protocol has a proxy contract, you should typically interact
        with it instead of the other contracts in the package.</CText
      >
    </CAlert>

    <CBox v-if="loading" py="20" textAlign="center">
      <CSpinner />
    </CBox>
    <CBox v-else>
      <CBox v-for="o in output" :key="o.title">
        <ContractStep
          v-if="o.title.startsWith('contract.')"
          :contracts="o.artifacts.contracts"
        />
        <ProvisionStep
          v-if="o.title.startsWith('provision.')"
          :imports="o.artifacts.imports"
        />
      </CBox>
    </CBox>
  </CBox>
</template>

<script lang="js">
import Vue from 'vue'
import axios from 'axios';
import pako from "pako";
import VersionSelect from "./Interact/VersionSelect";
import ContractStep from "./Interact/ContractStep";
import ProvisionStep from "./Interact/ProvisionStep";
import ConnectWallet from "./Interact/ConnectWallet";
import InteractCommand from "./Interact/InteractCommand";

export default {
  name: 'Interact',
  props: {
      p: {
          type: Object
      }
  },
  components: {
    VersionSelect,
    ContractStep,
    ProvisionStep,
    InteractCommand,
    ConnectWallet
  },
  data() {
    return {
      loading: true,
      ipfs: {},
      selectedVariant: {}
    };
  },
  watch:{
    async selectedVariant(){
      this.$store.dispatch('changeChainId', this.selectedVariant.chain_id, this.$toast)
      this.loading = true
      await axios.get(`https://usecannon.infura-ipfs.io/ipfs/${this.selectedVariant.ipfs.replace("ipfs://",'')}`, { responseType: 'arraybuffer' })
      .then(response => {        
        const uint8Array = new Uint8Array(response.data);
        const inflated = pako.inflate(uint8Array);
        const raw = new TextDecoder().decode(inflated);
        this.ipfs = JSON.parse(raw);
        this.loading = false;
        Vue.nextTick(()=>{
          this.scrollToAnchor();
        })
      })
      .catch(error => {
        console.error(error);
      });
    }
  },
  methods: {
    scrollToAnchor() {
      const anchor = window.location.hash.slice(1); // remove the '#' symbol
      if (anchor) {
        const element = document.getElementById(anchor);
        if (element) {
          element.scrollIntoView();
        }
      }
    }
  },
  computed: {
    latestVariant(){
      return this.p.tags.find(t => t.name === 'latest').variants.find(v => v.preset === 'main')
    },
    hasProxy(){
      return this.ipfs.state && JSON.stringify(this.ipfs.state).toLowerCase().includes('proxy')
    },
    output(){
      if(this.ipfs.state){
      const o = Object.entries(this.ipfs.state).map(([k,v]) => {
        if(k.startsWith('contract.')){
          return {title:k, artifacts: v.artifacts}
        }else if(k.startsWith('provision.')){
          return {title:k, artifacts: v.artifacts}
        }else{
          return null
        }
      }).filter(x=>!!x);
      return o
      }
    }
  }
}
</script>
