// packages/website/src/features/Packages/Versions.tsx
import { GetPackagesQuery } from '@/types/graphql/graphql';
import { FC } from 'react';
import { Box, Grid, GridItem, Heading } from '@chakra-ui/react';
import PackageNetworks from '@/components/PackageNetworks';
import PublishInfo from '@/features/Search/PackageCard/PublishInfo';
import _ from 'lodash';

type Package = GetPackagesQuery['packages'][0];
type Tag = Package['tags'][0];
type Variant = Tag['variants'][0];

export const Versions: FC<{
  p: Package;
}> = ({ p }) => {
  const variantsByTag = (tag: Tag): Record<string, Variant[]> => {
    return _.groupBy(tag.variants, 'preset');
  };

  const latestVariantByTag = (tag: Tag): Variant => {
    const a = variantsByTag(tag);
    const array: Variant[] = Object.values(a)[0];
    const result: Variant = array.reduce((max, current) => {
      return current.last_updated > max.last_updated ? current : max;
    }, array[0]);
    return result;
  };

  return (
    <Box>
      {p.tags.map((tag) => {
        return (
          <Box pb="3" mb="3" key={tag.id}>
            <Heading mb="3" size="md">
              {tag.name}
            </Heading>
            {Object.values(variantsByTag(tag)).map((variants: Variant[]) => {
              return (
                <Grid
                  pt="2"
                  mb="2"
                  v-for="variants in variantsByTag(tag)"
                  key={variants[0].preset}
                  borderTop="1px solid"
                  borderColor="gray.700"
                  template-columns="repeat(12, 1fr)"
                  gap="2"
                >
                  <GridItem col-span="2" pt="1">
                    <Heading size="sm" my="auto">
                      {variants[0].preset}
                    </Heading>
                  </GridItem>
                  <GridItem col-span="7">
                    <PackageNetworks download p={{ variants }} />
                  </GridItem>
                  <GridItem col-span="3" textAlign="right">
                    <PublishInfo lineBreak={true} p={latestVariantByTag(tag)} />
                  </GridItem>
                </Grid>
              );
            })}
          </Box>
        );
      })}
    </Box>
  );
};

// packages/website/components/search/Versions.vue
<template>
  <CBox>
    <CBox pb="3" mb="3" v-for="tag in p.tags" :key="tag.id">
      <CHeading mb="3" size="md">{{ tag.name }}</CHeading>
      <CGrid
        pt="2"
        mb="2"
        v-for="variants in variantsByTag(tag)"
        :key="variants[0].preset"
        borderTop="1px solid"
        borderColor="gray.700"
        template-columns="repeat(12, 1fr)"
        gap="2"
      >
        <CGridItem col-span="2" pt="1">
          <CHeading size="sm" my="auto">{{ variants[0].preset }}</CHeading>
        </CGridItem>
        <CGridItem col-span="7">
          <PackageNetworks download :p="{ variants }" />
        </CGridItem>
        <CGridItem col-span="3" textAlign="right">
          <PublishInfo :linebreak="true" :p="latestVariantByTag(tag)" />
        </CGridItem>
      </CGrid>
    </CBox>
  </CBox>
</template>

<script lang="js">
import PackageNetworks from "../shared/PackageNetworks"
import PublishInfo from "../shared/PublishInfo"

export default {
  name: 'Versions',
  props: {
      p: {
          type: Object
      }
  },
  methods: {
    variantsByTag(tag){
      return _.groupBy(tag.variants, 'preset')
    },
    latestVariantByTag(tag){
      const a = this.variantsByTag(tag)
      const array = Object.values(a)[0];
      const result = array.reduce((max, current) => {
        return (current.last_updated > max.last_updated) ? current : max;
      }, array[0]);
      return result
    },
  },
  components: {
    PackageNetworks,
    PublishInfo
  }
}
</script>
