// packages/website/src/features/Packages/FunctionInput/DefaultInput.tsx
import { FC, useEffect, useState } from 'react';
import { Input } from '@chakra-ui/react';
import { stringToHex } from 'viem';
import { AbiParameter } from 'abitype';

export const DefaultInput: FC<{
  handleUpdate: (value: string) => void;
  value?: string;
  inputType: AbiParameter['type'];
}> = ({ handleUpdate, value = '', inputType }) => {
  const [updateValue, setUpdateValue] = useState<string>(value);
  useEffect(() => {
    const bytes32Regex = /^0x[0-9a-fA-F]{64}$/;
    if (inputType == 'bytes32' && !bytes32Regex.test(updateValue)) {
      handleUpdate(stringToHex(updateValue, { size: 32 }));
    } else {
      handleUpdate(updateValue || '');
    }
  }, [updateValue]);
  return (
    <Input
      type="text"
      size="sm"
      bg="black"
      borderColor="whiteAlpha.400"
      value={updateValue}
      onChange={(e) => setUpdateValue(e.target.value)}
    />
  );
};

// packages/website/components/search/Interact/FunctionInput/DefaultInput.vue
<template>
  <CInput
    type="text"
    bg="black"
    v-model="value"
    borderColor="whiteAlpha.400"
    @input="updateValue"
  />
</template>
    
<script lang="js">
const ethers = require("ethers");

  export default {
    name: 'DefaultInput',
    data(){
      return {
        value: ''
      }
    },
    mounted(){
      this.updateValue()
    },
    methods: {
      updateValue() {
        const bytes32Regex = /^0x[0-9a-fA-F]{64}$/;
        if(this.inputType == 'bytes32' && !bytes32Regex.test(this.value)){
          this.$emit("update:value", ethers.utils.formatBytes32String(this.value));
        }else{
          this.$emit("update:value", this.value ? this.value : '');
        }
        
      }
    },
    props: {
        input: {
            type: Object
        },
        inputType: {
            type: String
        },
    }
  }
  </script>
