// packages/website/components/search/Cannonfile.vue
<template>
  <CBox>
    <CBox v-if="loading" py="20" textAlign="center">
      <CSpinner />
    </CBox>
    <CBox v-else-if="metadata.cannonfile">
      <client-only :placeholder="metadata.cannonfile">
        <prism-editor
          class="code-editor"
          v-model="metadata.cannonfile"
          :highlight="highlighter"
        ></prism-editor>
      </client-only>
    </CBox>
    <CBox v-else textAlign="center" py="20" opacity="0.5"
      >Cannonfile unavailable</CBox
    >
  </CBox>
</template>

<script lang="js">
import axios from 'axios';
import pako from "pako";

// import Prism Editor
import { PrismEditor } from 'vue-prism-editor';
import 'vue-prism-editor/dist/prismeditor.min.css'; // import the styles somewhere
import { highlight, languages } from 'prismjs/components/prism-core';
import 'prismjs/components/prism-toml';

export default {
  name: 'Cannonfile',
  props: {
    p: {
        type: Object
    }
  },
  components: {
    PrismEditor,
  },
  methods: {
    highlighter(code) {
      return  highlight(code, languages.toml);
    },
  },
  data() {
    return {
      loading: true,
      metadata: {}
    }
  },
  async mounted(){
    this.loading = true
    await axios.get(`https://ipfs.io/ipfs/${this.latestVariant.meta_url.replace("ipfs://",'')}`, { responseType: 'arraybuffer' })
    .then(response => {        
      const uint8Array = new Uint8Array(response.data);
      const inflated = pako.inflate(uint8Array);
      const raw = new TextDecoder().decode(inflated);
      this.metadata = JSON.parse(raw);
    })
    .catch(error => {
      console.error(error);
    });
    this.loading = false;
  },
  computed: {
    latestVariant(){
      return this.p.tags.find(t => t.name === 'latest').variants.find(v => v.preset === 'main')
    }
  }
}
</script>

// packages/website/src/features/Packages/Cannonfile.tsx
import { FC, useEffect, useMemo, useState } from 'react';
import { GetPackagesQuery } from '@/types/graphql/graphql';
import axios from 'axios';
import pako from 'pako';
import { Box, Spinner } from '@chakra-ui/react';
import Editor from 'react-simple-code-editor';
import { highlight, languages } from 'prismjs';
import 'prismjs/components/prism-toml';
import 'prismjs/themes/prism.css';

export const Cannonfile: FC<{
  p: GetPackagesQuery['packages'][0];
}> = ({ p }) => {
  const [loading, setLoading] = useState(false);
  const [metadata, setMetadata] = useState<any>({});

  const latestVariant = useMemo(() => {
    return p?.tags
      ?.find((t) => t?.name === 'latest')
      ?.variants.find((v) => v.preset === 'main');
  }, [p]);
  useEffect(() => {
    setLoading(true);

    const controller = new AbortController();

    axios
      .get(
        `https://ipfs.io/ipfs/${latestVariant?.meta_url?.replace(
          'ipfs://',
          ''
        )}`,
        { responseType: 'arraybuffer', signal: controller.signal }
      )
      .then((response) => {
        const uint8Array = new Uint8Array(response.data);
        const inflated = pako.inflate(uint8Array);
        const raw = new TextDecoder().decode(inflated);
        setMetadata(JSON.parse(raw));
      })
      .catch((error) => {
        console.error(error);
      })
      .finally(() => {
        setLoading(false);
      });

    return () => {
      controller.abort();
    };
  }, [latestVariant]);

  const highlighter = (code: string) => {
    return highlight(code, languages.toml, 'toml');
  };

  let view;
  if (loading) {
    view = (
      <Box py="20" textAlign="center">
        <Spinner />
      </Box>
    );
  } else {
    if (metadata?.cannonfile) {
      view = (
        <Box>
          <Editor
            highlight={highlighter}
            value={metadata?.cannonfile}
            disabled={true}
            onValueChange={() => {
              // nothing
            }}
          />
        </Box>
      );
    } else {
      view = (
        <Box textAlign="center" py="20" opacity="0.5">
          Cannonfile unavailable
        </Box>
      );
    }
  }
  return <Box>{view}</Box>;
};
