// packages/website/src/features/Packages/Contract.tsx
import React, { FC, useMemo, useState } from 'react';
import { Abi as AbiType } from 'abitype';
import { ChainArtifacts } from '@usecannon/builder';
import { useCopy } from '@/lib/copy';
import { Box, Button, Code, Flex, Heading, Link } from '@chakra-ui/react';
import { Abi } from '@/features/Packages/Abi';
import { Copy } from 'react-feather';

export const Contract: FC<{
  title: string;
  address: string;
  abi: AbiType;
  cannonOutputs: ChainArtifacts;
  chainId?: number;
}> = ({ title, address, abi, cannonOutputs, chainId }) => {
  const [show, setShow] = useState(false);
  const anchor = useMemo(() => {
    const currentHash = window.location.hash.replace('#', '').split('-')[0];
    return currentHash + '-' + address;
  }, [address]);

  const copyToClipboard = useCopy();
  const copy = () => {
    void copyToClipboard(address);
  };

  const adjustScroll = () => {
    setTimeout(() => {
      window.scrollBy(0, -120);
    }, 1);
  };

  return (
    <Box
      mb="4"
      borderRadius="4px"
      p="4"
      border="1px solid rgba(255,255,255,0.2)"
      bg="blackAlpha.500"
    >
      <Flex mb="2">
        <Heading id={anchor} mb="1" size="lg" display="inline-block">
          {title}
        </Heading>
        <Link
          href={'#' + anchor}
          fontSize="lg"
          ml="2"
          color="gray.400"
          onClick={adjustScroll}
        >
          #
        </Link>
        <Box ml="auto">
          <Code display="inline" bg="blackAlpha.800" color="whiteAlpha.800">
            {address}
          </Code>
          <div onClick={copy} className="copy-button">
            <Copy />
          </div>
        </Box>
      </Flex>
      {/*  TODO: Implement the collapse */}
      {/*<Collapse isOpen="show">*/}
      {show && (
        <Abi
          abi={abi}
          address={address}
          cannonOutputs={cannonOutputs}
          chainId={chainId}
        />
      )}
      {/*</Collapse>*/}
      <Button
        variant-color="blue"
        variant="outline"
        onClick={() => setShow(!show)}
        size="xs"
      >
        {show ? 'Hide' : 'Show'} contract functions
      </Button>
    </Box>
  );
};

// packages/website/components/search/Interact/Contract.vue
<template>
  <CBox
    mb="4"
    borderRadius="4px"
    p="4"
    border="1px solid rgba(255,255,255,0.2)"
    bg="blackAlpha.500"
  >
    <CFlex mb="2">
      <CHeading :id="anchor" mb="1" size="lg" display="inline-block">{{
        title
      }}</CHeading>
      <CLink
        :href="'#' + anchor"
        fontSize="lg"
        ml="2"
        color="gray.400"
        @click="adjustScroll"
        >#</CLink
      >
      <CBox ml="auto">
        <CCode bg="blackAlpha.800" color="whiteAlpha.800">{{
          address
        }}</CCode></CBox
      >
    </CFlex>
    <CCollapse :is-open="show">
      <Abi v-if="show" :abi="abi" :address="address" />
    </CCollapse>
    <CButton
      variant-color="blue"
      variant="outline"
      @click="show = !show"
      size="xs"
    >
      {{ show ? 'Hide' : 'Show' }} contract functions
    </CButton>
  </CBox>
</template>

<script lang="js">
import Abi from './Abi';

export default {
  name: 'Contract',
  data () {
    return {
      show: false
    }
  },
  components: {
    Abi
  },
  props: {
    title: {type: String },
    address: {type: String },
    abi: {type: Array },
  },
  computed: {
    anchor(){
      const currentHash = window.location.hash.replace("#","").split('-')[0]
      return currentHash + '-' + this.address
    }
  },
  methods: {
    adjustScroll(){
      setTimeout(() => {
        window.scrollBy(0, -120)
      },1)
    }
  }
}
</script>
