// packages/website/src/features/Packages/ContractStep.tsx
import { ChainArtifacts, ContractData, ContractMap } from '@usecannon/builder';
import { FC, useMemo } from 'react';
import { Box } from '@chakra-ui/react';
import { Contract } from '@/features/Packages/Contract';
import { Abi } from 'viem';

export const ContractStep: FC<{
  contracts?: ContractMap;
  cannonOutputs: ChainArtifacts;
}> = ({ contracts = {}, cannonOutputs }) => {
  const output: ({ title: string } & Pick<ContractData, 'address' | 'abi'>)[] =
    useMemo(() => {
      return Object.entries(contracts)
        .map(([k, v]) => ({ title: k, address: v.address, abi: v.abi }))
        .sort((a, b) => a.title.localeCompare(b.title));
    }, [contracts]);
  return (
    <Box mb="8">
      {output.map((o) => (
        <Contract
          key={JSON.stringify(o)}
          title={o.title}
          address={o.address}
          abi={o.abi as Abi}
          cannonOutputs={cannonOutputs}
        />
      ))}
    </Box>
  );
};

// packages/website/components/search/Interact/ContractStep.vue
<template>
  <CBox mb="8">
    <Contract
      v-for="o in output"
      :key="JSON.stringify(o)"
      :title="o.title"
      :address="o.address"
      :abi="o.abi"
      :cannonOutputs="cannonOutputs"
    />
  </CBox>
</template>

<script lang="js">
import Contract from './Contract';

export default {
  name: 'ContractStep',
  components: { Contract },
  props: {
    contracts: {
        type: Object
    },
    cannonOutputs: {
        type: Object
    },
  },
  computed: {
    output(){
      return Object.entries(this.contracts).map(([k,v]) => {
        return {title:k, address: v.address, abi: v.abi}
      })
      .sort((a, b) => a.title.localeCompare(b.title));
    }
  }
}
</script>
