// packages/website/src/features/Packages/FunctionOutput.tsx
import { FC } from 'react';
import { Box, Text, Flex } from '@chakra-ui/react';
import { AbiParameter } from 'abitype';
import { isArray, isObject } from 'lodash';

export const FunctionOutput: FC<{
  output: AbiParameter | readonly AbiParameter[];
  result: any;
}> = ({ output, result }) => {
  // Helper function to check if a value is an array of AbiParameters
  const isArrayOutput = (
    value: AbiParameter | readonly AbiParameter[]
  ): value is readonly AbiParameter[] => isArray(value);

  // Renders the output based on the type and structure of the item

  const ItemLabel: FC<{ name: string; type: string }> = ({ name, type }) => (
    <Flex alignItems={'center'} gap={1} fontSize="sm" mb={0}>
      <Text>{name}</Text>
      <Text fontSize="xs" color="whiteAlpha.700">
        {type}
      </Text>
    </Flex>
  );

  const renderOutput = (item: AbiParameter, value: any) => {
    // TUPLE
    if (item.type === 'tuple' && item.components) {
      return (
        <Box pl="4">
          {item.components.map((component: AbiParameter, idx) => (
            <FunctionOutput
              key={idx}
              output={component}
              result={isArray(value) ? value[idx] : value}
            />
          ))}
        </Box>
      );
      // ARRAY OF TUPLES
    } else if (item.type === 'tuple[]' && item.components) {
      return isArray(value)
        ? value.map((tupleItem, tupleIndex) => (
            <Box key={tupleIndex} pl="4">
              {item.components.map((component, compIdx) => (
                <FunctionOutput
                  key={compIdx}
                  output={component}
                  result={isArray(tupleItem) ? tupleItem[compIdx] : tupleItem}
                />
              ))}
            </Box>
          ))
        : null;
    } else {
      // OBJECTS
      if (isObject(value) && item.name && item.name in value) {
        console.log('value ', value);
        return <Text>{String(value[item.name])}</Text>;
      } else if (isArray(value)) {
        // ARRAYS
        return value.map((val, idx) => <Text key={idx}>{String(val)}</Text>);
      } else {
        // FALLBACK
        return (
          <Text pt="1" pb="3" fontSize="xs" color="whiteAlpha.900">
            {result !== null ? String(result) : '---'}
          </Text>
        );
      }
    }
  };
  return (
    <>
      {isArrayOutput(output) ? (
        output.map((item, index) => (
          <Box p={2} key={index}>
            <ItemLabel name={item.name} type={item.type} />

            {renderOutput(item, result)}
          </Box>
        ))
      ) : (
        <Box p={2}>
          <ItemLabel name={output.name || ''} type={output.type} />
          {renderOutput(output, result)}
        </Box>
      )}
    </>
  );
};

// packages/website/components/search/Interact/FunctionOutput.vue
<template>
  <div>
    <div v-if="isArray(output)">
      <div v-for="(item, index) in output" :key="index">
        <h4>
          {{ item.name }}
          <CText fontSize="xs" color="whiteAlpha.700" display="inline">{{
            item.internalType
          }}</CText>
        </h4>
        <div v-if="item.components">
          <div v-if="item.type==='tuple'">
            <div
              v-for="(component, componentIndex) in result"
              :key="componentIndex"
            >
              <FunctionOutput
                v-bind:output="item.components[componentIndex]"
                v-bind:result="component"
              />
            </div>
          </div>
          <div v-else-if="item.type==='tuple[]'">
            <div v-for="(resultItem, resultItemIndex) in result">
              <div
                v-for="(component, componentIndex) in resultItem"
                :key="resultItemIndex"
              >
                <FunctionOutput
                  v-bind:output="item.components[componentIndex]"
                  v-bind:result="component"
                />
              </div>
            </div>
          </div>
          <div v-else>
              {{ result }}
            </div>
        </div>
        <div v-else>
          {{ result }}
        </div>
      </div>
    </div>
    <div v-else-if="isObject(output)">
      <div>
        {{ output.name }}: {{ result }}
        <CText fontSize="xs" color="whiteAlpha.700" display="inline">{{
          output.internalType
        }}</CText>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'FunctionOutput',
  props: {
    output: {
      required: true,
    },
    result: {
      required: true,
    },
  },
  methods: {
    isArray(value) {
      return Array.isArray(value);
    },
    isObject(value) {
      return value && typeof value === 'object' && value.constructor === Object;
    },
  },
};
</script>
