// packages/website/src/features/Packages/FunctionInput.tsx
import { FC, useEffect, useMemo, useState } from 'react';
import { AbiParameter } from 'abitype';
import { Box, Flex, Link } from '@chakra-ui/react';
import { BoolInput } from '@/features/Packages/FunctionInput/BoolInput';
import { AddressInput } from '@/features/Packages/FunctionInput/AddressInput';
import { NumberInput } from '@/features/Packages/FunctionInput/NumberInput';
import { DefaultInput } from '@/features/Packages/FunctionInput/DefaultInput';
import { AddIcon, CloseIcon } from '@chakra-ui/icons';

export const FunctionInput: FC<{
  input: AbiParameter;
  valueUpdated: (value: any) => void;
}> = ({ input, valueUpdated }) => {
  const isArray = useMemo(() => !!input?.type?.endsWith('[]'), [input]);
  const [dataArray, setDataArray] = useState<{ id: number; val: any | null }[]>(
    [{ id: Date.now(), val: null }]
  );

  // const getValue = (index: number) => (isArray ? dataArray[index] : input);

  const add = () => {
    setDataArray([...dataArray, { id: Date.now(), val: null }]);
  };

  const remove = (index: number) => {
    setDataArray(dataArray.splice(index, 1));
  };

  useEffect(() => {
    valueUpdated(dataArray.map((item) => item.val));
  }, dataArray);

  const handleUpdate = (index: number | null, value: any) => {
    if (isArray) {
      const updatedArray = [...dataArray];
      updatedArray[index as number].val = value;
      setDataArray(updatedArray);
    } else {
      valueUpdated(value);
    }
  };

  const getInputComponent = (_handleUpdate: (value: any) => void) => {
    switch (true) {
      case input.type.startsWith('bool'):
        return <BoolInput handleUpdate={_handleUpdate} />;
      case input.type.startsWith('address'):
        return <AddressInput handleUpdate={_handleUpdate} />;
      case input.type.startsWith('int') || input.type.startsWith('uint'):
        return <NumberInput handleUpdate={_handleUpdate} />;
      default:
        return (
          <DefaultInput handleUpdate={_handleUpdate} inputType={input.type} />
        );
    }
  };

  let c;

  if (!isArray) {
    c = (
      <Flex direction="row" align="center">
        <Flex flex="1">
          {getInputComponent((value: any) => handleUpdate(null, value))}
        </Flex>
      </Flex>
    );
  } else {
    c = (
      <>
        <Box>
          {dataArray.map((inp, index) => {
            return (
              <Flex align="center" mb="4" flex="1" key={inp.id}>
                <Flex flex="1">
                  {getInputComponent((value: any) =>
                    handleUpdate(index, value)
                  )}
                  {dataArray.length > 1 && (
                    <Link onClick={() => remove(index)} ml="4">
                      <CloseIcon name="close" color="red.500" />{' '}
                    </Link>
                  )}
                </Flex>
              </Flex>
            );
          })}
        </Box>

        <Link onClick={add} float="right">
          <AddIcon name="add" color="green.500" />
        </Link>
      </>
    );
  }

  return <Box>{c}</Box>;
};

// packages/website/components/search/Interact/FunctionInput.vue
<template>
  <CBox>
    <CFlex v-if="!isArray" direction="row" align="center">
      <CFlex flex="1">
        <BoolInput
          v-if="input.type.startsWith('bool')"
          :input="getValue(input)"
          v-on:update:value="handleUpdate(null, $event)" />
        <AddressInput
          v-else-if="input.type.startsWith('address')"
          :input="getValue(input)"
          v-on:update:value="handleUpdate(null, $event)" />
        <NumberInput
          v-else-if="
            input.type.startsWith('int') || input.type.startsWith('uint')
          "
          :input="getValue(input)"
          :positive-only="input.type.startsWith('uint')"
          v-on:update:value="handleUpdate(null, $event)" />
        <DefaultInput
          v-else
          :input="getValue(input)"
          v-on:update:value="handleUpdate(null, $event)"
      /></CFlex>
    </CFlex>
    <CBox v-else>
      <CFlex
        align="center"
        mb="4"
        v-for="(inp, index) of array"
        flex="1"
        :key="inp.id"
      >
        <BoolInput
          v-if="input.type.startsWith('bool')"
          :input="getValue(inp)"
          v-on:update:value="handleUpdate(index, $event)" />
        <AddressInput
          v-else-if="input.type.startsWith('address')"
          :input="getValue(inp)"
          v-on:update:value="handleUpdate(index, $event)" />
        <NumberInput
          v-else-if="
            input.type.startsWith('int') || input.type.startsWith('uint')
          "
          :input="getValue(inp)"
          :positive-only="input.type.startsWith('uint')"
          v-on:update:value="handleUpdate(index, $event)" />
        <DefaultInput
          v-else
          :input="getValue(inp)"
          v-on:update:value="handleUpdate(index, $event)" />
        <CLink @click="remove(index, $event)" ml="4" v-if="array.length > 1">
          <c-icon name="close" color="red.500" /> </CLink
      ></CFlex>
    </CBox>

    <CLink v-if="isArray" @click="add()" float="right" v>
      <c-icon name="add" color="green.500" />
    </CLink>
  </CBox>
</template>
    
<script lang="js">
import Vue from 'vue';
import BoolInput from './FunctionInput/BoolInput';
import NumberInput from './FunctionInput/NumberInput';
import AddressInput from './FunctionInput/AddressInput';
import DefaultInput from './FunctionInput/DefaultInput';

export default {
  name: 'FunctionInput',
  components: {
    BoolInput,
    NumberInput,
    AddressInput,
    DefaultInput
  },
  props: {
    input: {
        type: Object
    }
  },
  data(){
    return {
      array: [{id: Date.now(), val: null}]
    }
  },
  computed: {
    isArray(){
      return this.input.type.endsWith('[]')
    }
  },
  methods: {
    handleUpdate(index, output){
      if(this.isArray){
        Vue.set(this.array, index, {id: this.array[index].id, val: output})
        this.$emit("update:value", this.array.map(a=>a.val));
      }else{
        this.$emit("update:value", output);
      }
    },
    getValue(index){
      if(this.isArray){
        this.array[index]
      }else{
        this.input
      }
    },
    add(){
      this.array.push({id: Date.now(), val: null})
      this.$emit("update:value", this.array.map(a=>a.val));
    },
    remove(index){
      this.array.splice(index, 1);
      this.$emit("update:value", this.array.map(a=>a.val));
    }
  }
}
</script>
