// packages/website/src/features/Packages/ProvisionStep.tsx
import { FC, useMemo } from 'react';
import { BundledOutput, ChainArtifacts } from '@usecannon/builder';
import { Box, Flex, Heading, Code } from '@chakra-ui/react';
import { BundledChainBuilderOutputs } from '@usecannon/builder';
import { Copy } from 'react-feather';
import { useCopy } from '@/lib/copy';
import { ContractStep } from '@/features/Packages/ContractStep';

export const ProvisionStep: FC<{
  cannonOutputs: ChainArtifacts;
  imports: BundledChainBuilderOutputs;
  chainId?: number;
}> = ({ cannonOutputs, imports, chainId }) => {
  const output: {
    title: string;
    url: BundledOutput['url'];
    contracts: BundledOutput['contracts'];
    imports: BundledOutput['imports'];
  }[] = useMemo(() => {
    return (
      Object.entries(imports).map(([k, v]) => {
        return {
          title: k,
          url: v.url,
          contracts: v.contracts,
          imports: v.imports,
        };
      }) || []
    );
  }, [imports]);

  const copy = useCopy();

  return (
    <Box mb="8">
      {output.map((o) => {
        return (
          <Box key={JSON.stringify(o)}>
            <Flex mb="2">
              <Heading v-if="o.title" mb="1" size="lg" display="inline-block">
                {o.title}
              </Heading>
              <Box ml="auto" v-if="o.url">
                <Code bg="blackAlpha.800" color="whiteAlpha.800">
                  {o.url.replace('ipfs://', '@ipfs:')}
                </Code>
                <div
                  onClick={async () => {
                    await copy(o.url.replace('ipfs://', '@ipfs:'));
                  }}
                  className="copy-button"
                >
                  <Copy />
                </div>
              </Box>
            </Flex>
            <ContractStep
              contracts={o.contracts}
              cannonOutputs={cannonOutputs}
              chainId={chainId}
            />

            {o.imports && (
              <ProvisionStep
                imports={o.imports}
                cannonOutputs={cannonOutputs}
              />
            )}
          </Box>
        );
      })}
    </Box>
  );
};

// packages/website/components/search/Interact/ProvisionStep.vue
<template>
  <CBox mb="8">
    <CBox v-for="o in output" :key="JSON.stringify(o)">
      <CFlex mb="2">
        <CHeading mb="1" size="lg" display="inline-block">{{
          o.title
        }}</CHeading>
        <CBox ml="auto">
          <CCode bg="blackAlpha.800" color="whiteAlpha.800">{{
            o.url.replace('ipfs://', '@ipfs:')
          }}</CCode></CBox
        >
      </CFlex>
      <ContractStep :contracts="o.contracts" />
      <ProvisionStep v-if="o.imports" :imports="o.imports" />
    </CBox>
  </CBox>
</template>

<script lang="js">
import ContractStep from './ContractStep';

export default {
  name: 'ProvisionStep',
  props: {
    imports: {
        type: Object
    }
  },
  components: {
    ContractStep
  },
  computed: {
    output(){
      return Object.entries(this.imports).map(([k,v]) => {
        return { title: k, url: v.url, contracts: v.contracts, imports: v.imports }
      })
    }
  }
}
</script>
