// packages/website/src/features/Packages/VersionSelect.tsx
import { GetPackagesQuery } from '@/types/graphql/graphql';
import { FC, useEffect, useMemo } from 'react';
import _ from 'lodash';
import chainsData from '@/constants/chainsData';
import { FormControl, Select } from '@chakra-ui/react';

type Package = GetPackagesQuery['packages'][0];
export type VersionInfo = {
  name: string;
  tag: string;
  preset: string;
  chain_id: number;
  ipfs: string;
  last_updated: any;
};

export const VersionSelect: FC<{
  p: Package;
  onChange: (value: VersionInfo) => void;
}> = ({ p, onChange }) => {
  const options = useMemo(() => {
    return _.flatten(
      p.tags.map((t) => {
        const _variants = [...(t.variants || [])];
        return (
          _variants
            .sort((a, b) => (a.chain_id > b.chain_id ? 1 : -1))
            .map((v) => {
              return {
                name: `${t.name} on ${chainsData[v.chain_id].name}${
                  v.preset !== 'main' ? ' (' + v.preset + ')' : ''
                }`,
                tag: t.name,
                preset: v.preset,
                chain_id: v.chain_id,
                ipfs: v.deploy_url,
                last_updated: v.last_updated,
              };
            }) || []
        );
      })
    );
  }, [p]);
  useEffect(() => {
    onChange(options[0]);
  }, [options]);
  return (
    <FormControl>
      <Select
        id="version-select"
        bg="black"
        borderColor="whiteAlpha.400"
        onChange={(e) => {
          onChange(JSON.parse(e.target.value));
        }}
        // v-model="currentValue"
      >
        {options.map((option) => {
          return (
            <option value={JSON.stringify(option)} key={JSON.stringify(option)}>
              {option.name}
            </option>
          );
        })}
      </Select>
    </FormControl>
  );
};

// packages/website/components/search/Interact/VersionSelect.vue
<template>
  <CFormControl>
    <CSelect
      id="country"
      bg="black"
      borderColor="whiteAlpha.400"
      v-model="currentValue"
    >
      <option
        v-for="option of options"
        :value="JSON.stringify(option)"
        :key="JSON.stringify(option)"
      >
        {{ option.name }}
      </option>
    </CSelect>
  </CFormControl>
</template>
    
<script lang="js">
import chains from '../../../helpers/chains';

  export default {
    name: 'VersionSelect',
    props: {
      p: {
          type: Object
      },
      value:{
        type: Object
      }
    },
    data(){
      return {
        currentValue: ''
      }
    },
    mounted(){
      this.currentValue = JSON.stringify(this.options[0])
    },
    watch: {
      options(){
        this.currentValue = JSON.stringify(this.options[0])
      },
      currentValue(){
        this.$emit('input', JSON.parse(this.currentValue));
      }
    },
    computed: {
      options() {
        return _.flatten(this.p.tags.map(t => {
          return t.variants.sort((a,b)=> a.chain_id > b.chain_id ? 1 : -1).map(v => {
            return {
              name: `${t.name} on ${chains[v.chain_id].name}${v.preset !== 'main' ? ' ('+v.preset+')': ''}`,
              tag: t.name,
              preset: v.preset,
              chain_id: v.chain_id,
              ipfs: v.deploy_url,
              last_updated: v.last_updated
            }
          })
        }))
      }
    }
  }
</script>
