// packages/website/components/search/Interact/FunctionInput/AddressInput.vue
<template>
  <CInput
    type="text"
    bg="black"
    v-model="value"
    :borderColor="isInvalid ? 'red.500' : 'whiteAlpha.400'"
    :is-invalid="isInvalid"
    placeholder="0x0000000000000000000000000000000000000000"
    @input="updateValue"
    :_focus="{
      borderColor: isInvalid ? 'red.500' : 'blue.300',
    }"
  />
</template>
    
<script lang="js">
const ethers = require("ethers");

  export default {
    name: 'AddressInput',
    data(){
      return {
        value: ''
      }
    },
    mounted(){
      this.updateValue()
    },
    methods: {
      updateValue() {
        this.$emit("update:value", this.value ? this.value : '');
      }
    },
    computed: {
      isInvalid() {
        if (!this.value.length) return false;
        return !ethers.utils.isAddress(this.value);
      }
    },
    props: {
        input: {
            type: Object
        }
    }
  }
  </script>

// packages/website/src/features/Packages/FunctionInput/AddressInput.tsx
import { isAddress } from 'viem';
import { Input } from '@chakra-ui/react';
import { FC, useEffect, useMemo, useState } from 'react';

export const AddressInput: FC<{
  handleUpdate: (value: string) => void;
  value?: string;
}> = ({ handleUpdate, value = '' }) => {
  const [updateValue, setUpdateValue] = useState<string>(value);
  const isInvalid = useMemo(
    () => !updateValue.length && !isAddress(updateValue),
    [updateValue]
  );
  useEffect(() => handleUpdate(updateValue), [updateValue]);

  return (
    <Input
      type="text"
      bg="black"
      borderColor={isInvalid ? 'red.500' : 'whiteAlpha.400'}
      is-invalid={isInvalid.toString()}
      placeholder="0x0000000000000000000000000000000000000000"
      value={updateValue}
      onChange={(e) => {
        setUpdateValue(e.target.value || '');
      }}
      _focus={{
        borderColor: isInvalid ? 'red.500' : 'blue.300',
      }}
    />
  );
};
