// packages/website/components/search/Interact/Function/BoolInput.vue
<template>
  <CFormControl mb="4">
    <CFormLabel color="white"
      ><CText display="inline" v-if="input.name">{{ input.name }}</CText>
      <CText
        v-if="input.type"
        fontSize="xs"
        color="whiteAlpha.700"
        display="inline"
      >
        {{ input.type }}</CText
      ></CFormLabel
    >
    <c-select
      borderColor="whiteAlpha.400"
      bg="black"
      v-model="value"
      @input="updateValue"
    >
      <option value="false">False</option>
      <option value="true">True</option>
    </c-select>
  </CFormControl>
</template>
    
<script lang="js">
const ethers = require("ethers");

  export default {
    name: 'BoolInput',
    data(){
      return {
        value: 'false'
      }
    },
    mounted(){
      this.updateValue()
    },
    methods: {
      updateValue() {
        this.$emit("update:value", this.value ? this.value : 'false');
      }
    },
    props: {
        input: {
            type: Object
        }
    }
  }
  </script>

// packages/website/src/features/Packages/FunctionInput/BoolInput.tsx
import { Select } from '@chakra-ui/react';
import { FC, useEffect, useState } from 'react';

export const BoolInput: FC<{
  handleUpdate: (value: boolean) => void;
  value?: boolean;
}> = ({ handleUpdate, value = false }) => {
  const [updateValue, setUpdateValue] = useState<boolean>(value);
  useEffect(() => handleUpdate(updateValue), [updateValue]);

  return (
    <Select
      borderColor="whiteAlpha.400"
      bg="black"
      onChange={(e) => setUpdateValue(e.target.value === 'true')}
    >
      <option value="false">False</option>
      <option value="true">True</option>
    </Select>
  );
};
